# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/88eca5a6-40ba-4cef-a995-639064e48cdf";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6289-3D23";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/lara/data" =
    { device = "/dev/disk/by-uuid/6e0753d6-9bbc-4183-b998-f2fb56adaf13";
      fsType = "xfs";
    };

  fileSystems."/home/lara/Documents" =
    { device = "/home/lara/data/Documents";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/lara/Projects" =
    { device = "/home/lara/data/Projects";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/lara/Media" =
    { device = "/home/lara/data/Media";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/lara/Downloads" =
    { device = "/home/lara/data/Downloads";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
